const cryptoList = {
    AAVE: "Aave",
    ADA: "Cardano",
    ALGO: "Algorand",
    APT: "Aptos",
    ATOM: "Cosmos",
    AVAX: "Avalanche",
    BCH: "Bitcoin Cash",
    BNB: "BNB",
    BTC: "Bitcoin",
    CAKE: "PancakeSwap",
    CHZ: "Chiliz",
    COMP: "Compound",
    CRO: "Cronos",
    DOGE: "Dogecoin",
    DOT: "Polkadot",
    ENJ: "Enjin Coin",
    ETC: "Ethereum Classic",
    ETH: "Ethereum",
    FIL: "Filecoin",
    FTM: "Fantom",
    FTT: "FTX Token",
    GRT: "The Graph",
    HBAR: "Hedera",
    ICP: "Internet Computer",
    KNC: "Kyber Network",
    KSM: "Kusama",
    LINK: "Chainlink",
    LTC: "Litecoin",
    LUNA: "Terra",
    MANA: "Decentraland",
    MATIC: "Polygon",
    MKR: "Maker",
    NEAR: "NEAR Protocol",
    OMG: "OMG Network",
    RUNE: "THORChain",
    SAND: "The Sandbox",
    SHIB: "Shiba Inu",
    SOL: "Solana",
    THETA: "Theta",
    TRX: "TRON",
    UNI: "Uniswap",
    USDC: "USD Coin",
    USDT: "Tether",
    VET: "VeChain",
    WBTC: "Wrapped Bitcoin",
    XLM: "Stellar",
    XMR: "Monero",
    XRP: "Ripple",
    XTZ: "Tezos",
    ZEC: "Zcash"
};
